# Generated by Django 5.1.3 on 2024-12-15 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menumodel',
            name='restaurants',
        ),
        migrations.AddField(
            model_name='menumodel',
            name='restaurants',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_menu', to='restaurants.restaurantmodel'),
            preserve_default=False,
        ),
    ]
