# Generated by Django 5.1.3 on 2024-12-14 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menumodel',
            name='restaurants',
        ),
        migrations.AddField(
            model_name='menumodel',
            name='restaurants',
            field=models.ManyToManyField(to='restaurants.restaurantmodel'),
        ),
    ]
