# Generated by Django 5.1.3 on 2024-12-05 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_categorymenumodel_menumodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menumodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='menu_images/'),
        ),
    ]
