# Generated by Django 5.1.3 on 2024-12-13 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_alter_managerandcouriermodel_first_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='managerandcouriermodel',
            options={'verbose_name': 'Manager and Courier', 'verbose_name_plural': 'Managers and Couriers'},
        ),
        migrations.AddField(
            model_name='managerandcouriermodel',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
