# Generated by Django 5.1.3 on 2024-12-06 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_managerandcouriermodel_delete_managerandcourier'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='managerandcouriermodel',
            options={'verbose_name': 'Manager_and_Courier', 'verbose_name_plural': 'Manager_and_Couriers'},
        ),
        migrations.AlterModelTable(
            name='managerandcouriermodel',
            table='manager_and_courier',
        ),
    ]
