# Generated by Django 5.1.3 on 2024-12-14 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_courier'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Courier',
        ),
    ]
