# Generated by Django 5.1.3 on 2024-12-15 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0003_delete_courier'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ManagerandCourierModel',
        ),
    ]
